# © 2018 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "account",  # required for testing auditlog
        "sale",  # required for testing mail_message_from_author
        "stock",  # required for testing base_extended_security
        "crm",  # required for testing mail_notification_no_action_button
        "admin_light_auditlog",
        "admin_light_base",
        "admin_light_bi_view_editor",
        "admin_light_calendar",
        "admin_light_company",
        "admin_light_filters",
        "admin_light_gamification",
        "admin_light_mail",
        "admin_light_mail_gmail",
        "admin_light_mail_outlook",
        "admin_light_user",
        "admin_light_web",
        "auth_oauth_authentik",
        "automatic_activity_deadlines",
        "base_extended_security",
        "base_extended_security_grid",
        "base_external_report_layout",
        "base_selection_label",
        "base_view_mode_restricted",
        "base_xml_rename",
        "currency_rate_update_boc",
        "ir_attachment_access_token_portal",
        "lang_fr_activated",
        "mail_activity_list_mark_done",
        "mail_activity_not_deleted",
        "mail_bot_no_pong",
        "mail_notification_no_action_button",
        "mail_message_from_author",
        "mail_notification_no_footer",
        "mail_template_default",
        "note_no_default_stage",
        # "numipack",
        # "numipack_account",
        # "numipack_account_enterprise",
        # "numipack_project",
        # "numipack_purchase",
        # "numipack_sale",
        # "numipack_stock",
        "portal_signature_auto",
        "private_data_group",
        #"profile_hr",
        "queue_job_auto_requeue",
        "test_http_request",
        "utm_archive",
        "web_email_field_new_tab",
        "dms_document_url",
        "event_allowed_ceu",
        "web_base_url_freeze",
    ],
    "installable": True,
}
